# Generated by Django 2.1 on 2020-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_video',
            field=models.FileField(default=' ', upload_to='courses/videos'),
        ),
    ]
